VKAvaloniaPlayer::ViewModels::PlayerControlViewModel::Player
int VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player._Stream
static VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.Player()
static int VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.GetPositionSeconds()
Referenced by VKAvaloniaPlayer.ViewModels.PlayerControlViewModel._Timer_Elapsed.
static void VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.SetStream(Models.AudioModel audioModel)
static bool VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.Play(Models.AudioModel model)
Referenced by VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.PlayerControlViewModel.
static bool VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.Play()
static bool VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.Stop()
static bool VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.Pause()
Referenced by VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.PlayerControlViewModel.
static void VKAvaloniaPlayer.ViewModels.PlayerControlViewModel.Player.SetVolume(double volume)